[versions]
mcp = "1.1.1"

[libraries]
junit = "org.junit.jupiter:junit-jupiter-engine:6.0.3"
mcp-client = { module = "io.modelcontextprotocol.sdk:mcp", version.ref = "mcp" }
mcp-json-jackson3 = { module = "io.modelcontextprotocol.sdk:mcp-json-jackson3", version.ref = "mcp" }
gson = "com.google.code.gson:gson:2.13.2"
bytebuddy = "net.bytebuddy:byte-buddy:1.18.8"

