name: Gradle

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [17, 21, 25]
        include:
          - os: macos-latest
            java: 17
          - os: windows-latest
            java: 17

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Cache Gradle packages
      uses: actions/cache@v5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', 'gradle/wrapper/gradle-wrapper.properties') }}
    - name: Install Xvfb (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install -y xvfb
    - name: Build with Gradle (Linux)
      if: runner.os == 'Linux'
      run: xvfb-run --auto-servernum ./gradlew clean build '-Pvaadin.productionMode' --stacktrace --info --no-daemon
    - name: Build with Gradle (macOS / Windows)
      if: runner.os != 'Linux'
      shell: bash
      run: ./gradlew clean build '-Pvaadin.productionMode' --stacktrace --info --no-daemon

